#!/usr/bin/env python3

import os
from config.env import DATABASE
from sqlite3 import connect as dbconnect
from cli_app import App
from commands.show import Show
from commands.add import Add
from commands.remove import Remove
from commands.edit import Edit

def database():
    """Database initialization."""
    # Checking if database file exists
    try:
        open('{}'.format(DATABASE['file']))
    except:
        os.system('mkdir {}'.format(DATABASE['dirname']))
        if os.name == 'nt': # windows
            print(DATABASE)
            os.system('type >> {}'.format(DATABASE['file']))
        else: # linux or mac
            os.system('touch {}'.format(DATABASE['file']))
    
    # Creating tables
    conn = dbconnect(DATABASE['file'])
    cur = conn.cursor()
    cur.execute('CREATE TABLE IF NOT EXISTS Tasks (description TEXT, fulldescription TEXT, completed INT)')
    conn.commit()
    conn.close()

class TasksApp(App):
    """Save your tasks and get it with terminal!!!"""

    def register_commands(self):
        self.add_command('show', Show)
        self.add_command('add', Add)
        self.add_command('remove', Remove)
        self.add_command('edit', Edit)

if __name__ == '__main__':
    database()
    app = TasksApp()
    app.run()
